# Generated by Django 6.0.2 on 2026-04-18 21:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpressionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='impressions/%Y/%m/%d/')),
                ('is_video', models.BooleanField(default=False)),
                ('impression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='impressions.impression')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['user'], name='impressions_user_id_6223f5_idx'),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['location'], name='impression_location_gist_idx'),
        ),
        migrations.AddConstraint(
            model_name='impression',
            constraint=models.UniqueConstraint(fields=('user_id', 'local_id'), name="local_id is unique in user's pool"),
        ),
    ]
