# Generated by Django 6.0.2 on 2026-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='description',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='impression',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
