# Generated by Django 6.0.2 on 2026-04-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressions', '0002_alter_impression_description_alter_impression_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='impression',
            name='impressions_user_id_6223f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='impression',
            name='impression_location_gist_idx',
        ),
    ]
